/* THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY. */
/* eslint-disable */
/* prettier-ignore */

import {MessageLoader, TypedIntlMessageGetter, HandlerFunction, HookFunction, LinkFunction} from '@discord/intl';

export declare const messagesLoader: MessageLoader;

declare const messages: {
  /**
   * Key: `eyPWtr`
   * 
   * ### Definition
   * ```text
   * {count, plural, =1 {# attachment} other {# attachments}}
   * ```
   * 
   * **Translated in all locales**
   */
  'EDITMESSAGEATTACHMENTS_COUNT_ATTACHMENTS': TypedIntlMessageGetter<{count: any | number | string}>,
  /**
   * Key: `HSYibm`
   * 
   * ### Definition
   * ```text
   * Clear the upload queue when the edit is cancelled
   * ```
   * 
   * **Translated in all locales**
   */
  'EDITMESSAGEATTACHMENTS_SETTINGS_CLEAR_ON_CANCEL_TITLE': TypedIntlMessageGetter<{}>,
};
export default messages;