/* THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY. */
/* eslint-disable */
/* prettier-ignore */

import {MessageLoader, TypedIntlMessageGetter, HandlerFunction, HookFunction, LinkFunction} from '@discord/intl';

export declare const messagesLoader: MessageLoader;

declare const messages: {
  /**
   * Key: `/+Ca8P`
   * 
   * ### Definition
   * ```text
   * Center
   * ```
   * 
   * **Translated in all locales**
   */
  'JUMPTOFIRSTMESSAGE_SETTINGS_ALIGNMENT_CENTER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `3sMimJ`
   * 
   * ### Definition
   * ```text
   * Left
   * ```
   * 
   * **Translated in all locales**
   */
  'JUMPTOFIRSTMESSAGE_SETTINGS_ALIGNMENT_LEFT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `A6D4Fx`
   * 
   * ### Definition
   * ```text
   * The horizontal alignment of the button in the channels.
   * ```
   * 
   * **Translated in all locales**
   */
  'JUMPTOFIRSTMESSAGE_SETTINGS_ALIGNMENT_NOTE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `hM1n5u`
   * 
   * ### Definition
   * ```text
   * Right
   * ```
   * 
   * **Translated in all locales**
   */
  'JUMPTOFIRSTMESSAGE_SETTINGS_ALIGNMENT_RIGHT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `wdCH3N`
   * 
   * ### Definition
   * ```text
   * Button Alignment
   * ```
   * 
   * **Translated in all locales**
   */
  'JUMPTOFIRSTMESSAGE_SETTINGS_ALIGNMENT_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `2DPMYG`
   * 
   * ### Definition
   * ```text
   * Will jump to the last unread message, if available, before jumping to the first message of the channel.
   * ```
   * 
   * **Translated in all locales**
   */
  'JUMPTOFIRSTMESSAGE_SETTINGS_JUMP_TO_UNREAD_NOTE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `LMieWl`
   * 
   * ### Definition
   * ```text
   * Whether to display the button in threads only. It's recommended to leave this option enabled.
   * ```
   * 
   * **Translated in all locales**
   */
  'JUMPTOFIRSTMESSAGE_SETTINGS_THREADS_ONLY_NOTE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `YAVC8v`
   * 
   * ### Definition
   * ```text
   * Only show in threads
   * ```
   * 
   * **Translated in all locales**
   */
  'JUMPTOFIRSTMESSAGE_SETTINGS_THREADS_ONLY_TITLE': TypedIntlMessageGetter<{}>,
};
export default messages;