/* THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY. */
/* eslint-disable */
/* prettier-ignore */

import {MessageLoader, TypedIntlMessageGetter, HandlerFunction, HookFunction, LinkFunction} from '@discord/intl';

export declare const messagesLoader: MessageLoader;

declare const messages: {
  /**
   * Key: `XuiZHh`
   * 
   * ### Definition
   * ```text
   * Cleared everything!
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_CLEARED_EVERYTHING_TOAST': TypedIntlMessageGetter<{}>,
  /**
   * Key: `8l3LS0`
   * 
   * ### Definition
   * ```text
   * Cleared {type}!
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_CLEARED_TOAST': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `MwKaY2`
   * 
   * ### Definition
   * ```text
   * Something went wrong!
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_ERROR_GENERIC_TOAST': TypedIntlMessageGetter<{}>,
  /**
   * Key: `NpgjTU`
   * 
   * ### Definition
   * ```text
   * This will mark everything as read. Are you sure you want to continue?
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_MARK_ALL_READ_DESCRIPTION': TypedIntlMessageGetter<{}>,
  /**
   * Key: `XEAJUF`
   * 
   * ### Definition
   * ```text
   * Read All
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_READ_ALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `MMLqER`
   * 
   * ### Definition
   * ```text
   * Direct Messages
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_READ_TYPE_DM': TypedIntlMessageGetter<{}>,
  /**
   * Key: `V0c5Ul`
   * 
   * ### Definition
   * ```text
   * Channels
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_READ_TYPE_GUILD_CHANNEL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `CgkcYW`
   * 
   * ### Definition
   * ```text
   * Events
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_READ_TYPE_GUILD_EVENT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `h52IRE`
   * 
   * ### Definition
   * ```text
   * Onboarding Questions
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_READ_TYPE_GUILD_ONBOARDING_QUESTION': TypedIntlMessageGetter<{}>,
  /**
   * Key: `VL4TwM`
   * 
   * ### Definition
   * ```text
   * Muted Servers
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_READ_TYPE_MUTED_GUILD': TypedIntlMessageGetter<{}>,
  /**
   * Key: `iFygr6`
   * 
   * ### Definition
   * ```text
   * Ask for confirmation before marking as read
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_SETTINGS_ASK_CONFIRM_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `naqYGh`
   * 
   * ### Definition
   * ```text
   * Disables the tooltip as well.
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_SETTINGS_DISPLAY_TEXT_NOTE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `682GiI`
   * 
   * ### Definition
   * ```text
   * Display text instead of an icon
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_SETTINGS_DISPLAY_TEXT_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `xGX8+v`
   * 
   * ### Definition
   * ```text
   * Edit Blacklist
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_SETTINGS_EDIT_BLACKLIST': TypedIntlMessageGetter<{}>,
  /**
   * Key: `sjzDl5`
   * 
   * ### Definition
   * ```text
   * Use a round button
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_SETTINGS_ROUND_BUTTON_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `CzdMQE`
   * 
   * ### Definition
   * ```text
   * {count} servers won't get marked as read.
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_SETTINGS_SERVER_BLACKLIST_NOTE': TypedIntlMessageGetter<{count: any}>,
  /**
   * Key: `xmn8LS`
   * 
   * ### Definition
   * ```text
   * Server Blacklist
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_SETTINGS_SERVER_BLACKLIST_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `DeDfJi`
   * 
   * ### Definition
   * ```text
   * Show a confirmation toast
   * ```
   * 
   * **Translated in all locales**
   */
  'READALLBUTTON_SETTINGS_SHOW_TOAST_TITLE': TypedIntlMessageGetter<{}>,
};
export default messages;